### ISSUE TITLE
Feature request: Add support for .bowerrc

### ISSUE THREAD

**Issue by lifenstein** [ChrisKraljevicD2L/bower-dependency-graph#10]
Please add support for .bowerrc configurations like specifying alternate directory paths for bower_components, like so:

```
{
  "directory": "app/bower_components"
}
```

**Comment by ChrisKraljevicD2L** [comment]
Added :+1:
#11 
[v0.2.0](https://github.com/ChrisKraljevicD2L/bower-dependency-graph/releases/tag/v0.2.0)

**Comment by lifenstein** [comment]
Hi Chris,
Thanks for the quick response, but it seems to have lost the ability to do a recursive graph after this change.

Here's the repo I'm using it for: https://github.com/uqlibrary/uqlibrary-pages

With v0.1.2, I needed to do this:

```
mkdir uqlibrary-pages && cd $_
git clone https://github.com/uqlibrary/uqlibrary-pages.git .
npm i -g bower bower-dependency-graph@0.1.2
npm i
cp bower.json app/bower.json
cd app
bower-dependency-graph -o
```

This would generate a 56000+ character json file, which included all the nested dependencies.

With v0.2.0, I don't need to do the `cp` and `cd app`, but I only get just above 3000 characters in the ouput, as it only contains the first level dependencies.

**Comment by ChrisKraljevicD2L** [comment]
Hey Ashley,

I see what's causing recursive graphs to break. I forgot to replace [this string of `'bower_components'`](https://github.com/ChrisKraljevicD2L/bower-dependency-graph/blob/master/index.js#L91) with the variable `bowerComponentsPath`. I'll be releasing `v0.2.1` to fix this shortly.

Edit: [`v0.2.1`](https://www.npmjs.com/package/bower-dependency-graph) has been released

**Comment by lifenstein** [comment]
It's working, thanks Chris!
